const translations = {
    en: {
        title: "BMW Life: Driven by Passion",
        brand_main: "Performance",
        brand_sub: "Sheer Driving Pleasure",
        nav_home: "Home",
        nav_m3: "M3 Series",
        m3_e30: "E30 M3",
        m3_e46: "E46 M3",
        m3_e92: "E90/E92/E93 M3",
        m3_f80: "F80 M3",
        m3_g80: "G80 M3",
        nav_m4: "M4 Series",
        m4_competition: "M4 Competition",
        m4_xdrive: "M4 Competition with M xDrive",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 Coupe",
        nav_m5: "M5 Series",
        m5_e28: "E28 M5 (1985-1988)",
        m5_e34: "E34 M5 (1988-1995)",
        m5_e39_1: "E39 M5 (1998-2003)",
        m5_e39_2: "E39 M5 (1998-2003)",
        m5_e39_3: "E39 M5 (1998-2003)",
        project_gallery: "Project Gallery",
        box_drive: "BMW PANORAMIC DRIVE <br> iDRIVE",
        learn_more: "Learn More↗",
        guide_title: "The Guide",
        guide_sub: "The Heart of Joy: Redefining the Driving Pleasure",
        hidden_title: "The Guide",
        hidden_sub: "BMW Hidden Features: Discover Clever Features in your BMW",
        stay_updated: "STAY UP TO DATE WITH BMW.",
        bmw_emblem: "Iconic BMW Emblem.",
        bmw_art_basel: "Art Basel Basel 2025",
        bmw_perfume: "The first BMW fragrance",
        bmw_charging: "Sheer charging pleasure",
        bmw_spotify: "Spotify Playlist",
        tech_title_1: "Technology",
        tech_sub_1: "BMW Mechanical Masterpiece: 15 Exceptional BMW Engines",
        tech_title_2: "Technology",
        tech_sub_2: "Legacy of Light: BMW's Evolving Headlight Story",
        bmw_intelligence: "BMW Intelligence",
        bmw_intelligence_sub: "An Evolution of Control and Intelligent Connectivity",
        lang_en: "English",
        lang_es: "Español",
        lang_de: "Deutsch",
        lang_it: "Italiano",
        lang_fr: "Français",
        lang_zh: "Chinese",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service"
    },
    es: {
        title: "BMW Vida: Impulsado por la Pasión",
        brand_main: "Rendimiento",
        brand_sub: "Puro Placer de Conducir",
        nav_home: "Inicio",
        nav_m3: "Serie M3",
        m3_e30: "M3 E30",
        m3_e46: "M3 E46",
        m3_e92: "M3 E90/E92/E93",
        m3_f80: "M3 F80",
        m3_g80: "M3 G80",
        nav_m4: "Serie M4",
        m4_competition: "M4 Competición",
        m4_xdrive: "M4 Competición con M xDrive",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 Coupé",
        nav_m5: "Serie M5",
        m5_e28: "M5 E28 (1985-1988)",
        m5_e34: "M5 E34 (1988-1995)",
        m5_e39_1: "M5 E39 (1998-2003)",
        m5_e39_2: "M5 E39 (1998-2003)",
        m5_e39_3: "M5 E39 (1998-2003)",
        project_gallery: "Galería del Proyecto",
        box_drive: "CONDUCCIÓN PANORÁMICA BMW <br> iDRIVE",
        learn_more: "Aprende Más↗",
        guide_title: "La Guía",
        guide_sub: "El Corazón del Placer: Redefiniendo la Conducción",
        hidden_title: "La Guía",
        hidden_sub: "Funciones Ocultas de BMW: Descubre Características Inteligentes",
        stay_updated: "MANTÉNGASE AL DÍA CON BMW.",
        bmw_emblem: "Emblema Icónico de BMW.",
        bmw_art_basel: "Art Basel Basilea 2025",
        bmw_perfume: "La primera fragancia de BMW",
        bmw_charging: "Puro placer de carga",
        bmw_spotify: "Lista de reproducción de Spotify",
        tech_title_1: "Tecnología",
        tech_sub_1: "Obra Maestra Mecánica: 15 Motores BMW Excepcionales",
        tech_title_2: "Tecnología",
        tech_sub_2: "Legado de Luz: Evolución de los Faros BMW",
        bmw_intelligence: "Inteligencia BMW",
        bmw_intelligence_sub: "Evolución del Control y Conectividad Inteligente",
        lang_en: "Inglés",
        lang_es: "Español",
        lang_de: "Alemán",
        lang_it: "Italiano",
        lang_fr: "Francés",
        lang_zh: "Chino",
        footer_privacy: "Política de Privacidad",
        footer_terms: "Términos del Servicio"
    },
    de: {
        title: "BMW Leben: Angetrieben von Leidenschaft",
        brand_main: "Leistung",
        brand_sub: "Die schiere Fahrfreude",
        nav_home: "Startseite",
        nav_m3: "M3 Serie",
        m3_e30: "M3 E30",
        m3_e46: "M3 E46",
        m3_e92: "M3 E90/E92/E93",
        m3_f80: "M3 F80",
        m3_g80: "M3 G80",
        nav_m4: "M4 Serie",
        m4_competition: "M4 Competition",
        m4_xdrive: "M4 Competition mit M xDrive",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 Coupé",
        nav_m5: "M5 Serie",
        m5_e28: "M5 E28 (1985-1988)",
        m5_e34: "M5 E34 (1988-1995)",
        m5_e39_1: "M5 E39 (1998-2003)",
        m5_e39_2: "M5 E39 (1998-2003)",
        m5_e39_3: "M5 E39 (1998-2003)",
        project_gallery: "Projektgalerie",
        box_drive: "BMW PANORAMIC DRIVE <br> iDRIVE",
        learn_more: "Erfahren Sie mehr↗",
        guide_title: "Der Leitfaden",
        guide_sub: "Das Herz der Freude: Fahren neu definiert",
        hidden_title: "Der Leitfaden",
        hidden_sub: "Versteckte BMW Funktionen: Entdecken Sie clevere Features",
        stay_updated: "BLEIBEN SIE AUF DEM LAUFENDEN MIT BMW.",
        bmw_emblem: "Ikonisches BMW Emblem.",
        bmw_art_basel: "Art Basel Basel 2025",
        bmw_perfume: "Das erste BMW Parfüm",
        bmw_charging: "Die schiere Ladefreude",
        bmw_spotify: "Spotify-Wiedergabeliste",
        tech_title_1: "Technologie",
        tech_sub_1: "Mechanisches Meisterwerk: 15 außergewöhnliche BMW Motoren",
        tech_title_2: "Technologie",
        tech_sub_2: "Erbe des Lichts: Die Evolution der BMW Scheinwerfer",
        bmw_intelligence: "BMW Intelligenz",
        bmw_intelligence_sub: "Evolution der intelligenten Steuerung und Konnektivität",
        lang_en: "Englisch",
        lang_es: "Spanisch",
        lang_de: "Deutsch",
        lang_it: "Italienisch",
        lang_fr: "Französisch",
        lang_zh: "Chinesisch",
        footer_privacy: "Datenschutz-Bestimmungen",
        footer_terms: "Nutzungsbedingungen"
    },
    it: {
        title: "BMW Life: Guidati dalla Passione",
        brand_main: "Prestazioni",
        brand_sub: "Il puro piacere di guidare",
        nav_home: "Home",
        nav_m3: "Serie M3",
        m3_e30: "M3 E30",
        m3_e46: "M3 E46",
        m3_e92: "M3 E90/E92/E93",
        m3_f80: "M3 F80",
        m3_g80: "M3 G80",
        nav_m4: "Serie M4",
        m4_competition: "M4 Competition",
        m4_xdrive: "M4 Competition con M xDrive",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 Coupé",
        nav_m5: "Serie M5",
        m5_e28: "M5 E28 (1985-1988)",
        m5_e34: "M5 E34 (1988-1995)",
        m5_e39_1: "M5 E39 (1998-2003)",
        m5_e39_2: "M5 E39 (1998-2003)",
        m5_e39_3: "M5 E39 (1998-2003)",
        project_gallery: "Galleria Progetti",
        box_drive: "BMW PANORAMIC DRIVE <br> iDRIVE",
        learn_more: "Scopri di più↗",
        guide_title: "La Guida",
        guide_sub: "Il Cuore della Gioia: Ridefinire il Piacere di Guidare",
        hidden_title: "La Guida",
        hidden_sub: "Funzioni Nascoste BMW: Scopri le Caratteristiche Intelligenti",
        stay_updated: "RESTA AGGIORNATO CON BMW.",
        bmw_emblem: "Iconico Emblema BMW.",
        bmw_art_basel: "Art Basel Basilea 2025",
        bmw_perfume: "Il primo profumo BMW",
        bmw_charging: "Puro piacere di ricarica",
        bmw_spotify: "Playlist Spotify",
        tech_title_1: "Tecnologia",
        tech_sub_1: "Capolavoro Meccanico: 15 Eccezionali Motori BMW",
        tech_title_2: "Tecnologia",
        tech_sub_2: "Eredità di Luce: L'evoluzione dei Fari BMW",
        bmw_intelligence: "BMW Intelligence",
        bmw_intelligence_sub: "Un'evoluzione del Controllo e della Connettività Intelligente",
        lang_en: "Inglese",
        lang_es: "Spagnolo",
        lang_de: "Tedesco",
        lang_it: "Italiano",
        lang_fr: "Francese",
        lang_zh: "Cinese",
        footer_privacy: "Informativa sulla Privacy",
        footer_terms: "Termini di Servizio"
    },
    fr: {
        title: "BMW Life : Passionnément Vôtre",
        brand_main: "Performance",
        brand_sub: "Le plaisir de conduire",
        nav_home: "Accueil",
        nav_m3: "Série M3",
        m3_e30: "M3 E30",
        m3_e46: "M3 E46",
        m3_e92: "M3 E90/E92/E93",
        m3_f80: "M3 F80",
        m3_g80: "M3 G80",
        nav_m4: "Série M4",
        m4_competition: "M4 Competition",
        m4_xdrive: "M4 Competition avec M xDrive",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 Coupé",
        nav_m5: "Série M5",
        m5_e28: "M5 E28 (1985-1988)",
        m5_e34: "M5 E34 (1988-1995)",
        m5_e39_1: "M5 E39 (1998-2003)",
        m5_e39_2: "M5 E39 (1998-2003)",
        m5_e39_3: "M5 E39 (1998-2003)",
        project_gallery: "Galerie de Projets",
        box_drive: "BMW PANORAMIC DRIVE <br> iDRIVE",
        learn_more: "En savoir plus↗",
        guide_title: "Le Guide",
        guide_sub: "Le Cœur de la Joie : Redéfinir le Plaisir de Conduire",
        hidden_title: "Le Guide",
        hidden_sub: "Fonctions Cachées BMW : Découvrez des Fonctions Astucieuses",
        stay_updated: "RESTEZ À JOUR AVEC BMW.",
        bmw_emblem: "Emblème Iconique BMW.",
        bmw_art_basel: "Art Basel Bâle 2025",
        bmw_perfume: "Le premier parfum BMW",
        bmw_charging: "Le plaisir de la recharge",
        bmw_spotify: "Playlist Spotify",
        tech_title_1: "Technologie",
        tech_sub_1: "Chef-d'œuvre Mécanique : 15 Moteurs BMW Exceptionnels",
        tech_title_2: "Technologie",
        tech_sub_2: "Héritage de Lumière : L'évolution des Phares BMW",
        bmw_intelligence: "BMW Intelligence",
        bmw_intelligence_sub: "Une Évolution du Contrôle et de la Connectivité Intelligente",
        lang_en: "Anglais",
        lang_es: "Espagnol",
        lang_de: "Allemand",
        lang_it: "Italien",
        lang_fr: "Français",
        lang_zh: "Chinois",
        footer_privacy: "Politique de Confidentialité",
        footer_terms: "Conditions d'Utilisation"
    },
    zh: {
        title: "BMW 生活：激情驱动",
        brand_main: "性能",
        brand_sub: "纯粹驾驶乐趣",
        nav_home: "首页",
        nav_m3: "M3 系列",
        m3_e30: "E30 M3",
        m3_e46: "E46 M3",
        m3_e92: "E90/E92/E93 M3",
        m3_f80: "F80 M3",
        m3_g80: "G80 M3",
        nav_m4: "M4 系列",
        m4_competition: "M4 雷霆版",
        m4_xdrive: "M4 雷霆版 (含 M xDrive)",
        m4_cs: "M4 CS",
        m4_csl: "M4 CSL",
        m4_coupe: "M4 双门轿跑车",
        nav_m5: "M5 系列",
        m5_e28: "E28 M5 (1985-1988)",
        m5_e34: "E34 M5 (1988-1995)",
        m5_e39_1: "E39 M5 (1998-2003)",
        m5_e39_2: "E39 M5 (1998-2003)",
        m5_e39_3: "E39 M5 (1998-2003)",
        project_gallery: "项目库",
        box_drive: "BMW 全景驾驶视界 <br> iDRIVE",
        learn_more: "了解更多↗",
        guide_title: "指南",
        guide_sub: "悦之心：重新定义驾驶乐趣",
        hidden_title: "指南",
        hidden_sub: "BMW 隐藏功能：发现您车内的巧妙设计",
        stay_updated: "关注 BMW 最新动态。",
        bmw_emblem: "经典的 BMW 标志。",
        bmw_art_basel: "2025 巴塞尔艺术展",
        bmw_perfume: "首款 BMW 香氛",
        bmw_charging: "纯粹充电乐趣",
        bmw_spotify: "Spotify 播放列表",
        tech_title_1: "科技",
        tech_sub_1: "机械杰作：15 款卓越的 BMW 发动机",
        tech_title_2: "科技",
        tech_sub_2: "光之传承：BMW 大灯进化史",
        bmw_intelligence: "BMW 智能",
        bmw_intelligence_sub: "控制与智能互联的演进",
        lang_en: "英语",
        lang_es: "西班牙语",
        lang_de: "德语",
        lang_it: "意大利语",
        lang_fr: "法语",
        lang_zh: "中文",
        footer_privacy: "隐私政策",
        footer_terms: "服务条款"
    }
};
function applyTranslations(lang) {
    const dictionary = translations[lang];
    if (!dictionary) return;

    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        const translation = dictionary[key];
        if (translation) {
            element.innerHTML = translation;
        }
    });
}

document.querySelectorAll('[data-lang]').forEach(link => {
    link.addEventListener('click', (event) => {
        event.preventDefault();
        const lang = link.getAttribute('data-lang');
        applyTranslations(lang);
        localStorage.setItem('bmw_lang', lang);
    });
});

function initializeLanguage() {
    const savedLang = localStorage.getItem('bmw_lang');
    if (savedLang) {
        applyTranslations(savedLang);
    } else {
        applyTranslations('en');
    }
}

// Ensure the DOM is fully loaded before running
document.addEventListener('DOMContentLoaded', initializeLanguage);


